sistemaDual/Controllers/EmpresasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using sistemaDual.Data;
using sistemaDual.Interfaces;
using sistemaDual.Models;
using sistemaDual.Models.ViewModels;
using sistemaDual.Utilidades.Response;

namespace sistemaDual.Controllers
{
    public class EmpresasController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IEmpresaService _empresaService;

        public EmpresasController(IMapper mapper, IEmpresaService empresaService)
        {
            _mapper = mapper;
            _empresaService = empresaService;   
        }

        //
        public IActionResult Index()
        {
            return View();
        }

        //
        [HttpGet]
        public async Task<IActionResult> Lista()
        {
            List<EmpresaViewModel> empresaViewModels = _mapper.Map<List<EmpresaViewModel>>(await _empresaService.Lista());
            return StatusCode(StatusCodes.Status200OK, new { data = empresaViewModels });
        }

        //
        [HttpPost]
        public async Task<IActionResult> Crear([FromForm] string modelo)
        {
            GenericResponse<EmpresaViewModel> response = new GenericResponse<EmpresaViewModel>();
            try
            {
                EmpresaViewModel empresaVM = JsonConvert.DeserializeObject<EmpresaViewModel>(modelo);

                Empresa empresa_creada = await _empresaService.Crear(_mapper.Map<Empresa>(empresaVM));

                empresaVM = _mapper.Map<EmpresaViewModel>(empresa_creada);

                response.Estado = true;
                response.Objeto = empresaVM;

            }catch(Exception ex)
            {
                response.Estado = false;
                response.Mensaje = ex.Message;
            }
            return StatusCode(StatusCodes.Status200OK, response);
        }

        //
        [HttpPut]
        public async Task<IActionResult> Editar([FromForm] string modelo)
        {
            GenericResponse<EmpresaViewModel> response = new GenericResponse<EmpresaViewModel>();

            try
            {
                EmpresaViewModel empresaVM = JsonConvert.DeserializeObject<EmpresaViewModel>(modelo);
                Empresa empresa_editada = await _empresaService.Editar(_mapper.Map<Empresa>(empresaVM));

                empresaVM = _mapper.Map<EmpresaViewModel>(empresa_editada);
                response.Estado = true;
                response.Objeto = empresaVM;
            }
            catch(Exception ex)
            {
                response.Estado = false;
                response.Mensaje = ex.Message;
            }
            return StatusCode(StatusCodes.Status200OK, response);
        }

        //
        [HttpDelete]
        public async Task<IActionResult> Eliminar(int empresaID)
        {
            GenericResponse<string> response = new GenericResponse<string>();
            try
            {
                response.Estado = await _empresaService.Eliminar(empresaID);
            }
            catch(Exception ex)
            {
                response.Estado = false;
                response.Mensaje = ex.Message;
            }
            return StatusCode(StatusCodes.Status200OK, response);
        }
    }
}

sistemaDual/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Sistema Dual - @ViewData["Title"]</title>

    <!-- Custom fonts for this template-->
    <link href="~/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/css/sb-admin-2.css" rel="stylesheet">
    <link href="~/vendor/toastr/toastr.min.css" rel="stylesheet">
    <link href="~/vendor/sweetalert/sweetalert.css" rel="stylesheet">
    @await RenderSectionAsync("Estilos", required: false)
</head>
<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                <div class="sidebar-brand-icon">
                    <i class="fas fa-desktop"></i>
                </div>
                <div class="sidebar-brand-text mx-3">MI TIENDA</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Dashboard")">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- Nav Item - Administración Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseAdministracion">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Administración</span>
                </a>
                <div id="collapseAdministracion" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" href="@Url.Action("Index","AlumnosDuales")">Alumnos</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Inventario Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUE">
                    <i class="fas fa-fw fa-clipboard-list"></i>
                    <span>Unidades Económicas</span>
                </a>
                <div id="collapseUE" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-controller="Empresas" asp-action="Index">Empresas</a>
                        <a class="collapse-item" asp-controller="MentoresEmpresariales" asp-action="Index">Mentores</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Venta Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseInst">
                    <i class="fas fa-fw fa-tags"></i>
                    <span>Institución</span>
                </a>
                <div id="collapseInst" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-controller="Universidades" asp-action="Index">Universidad</a>
                        <a class="collapse-item" asp-controller="ProgramasEducativos" asp-action="Index">ProgramaEducativo</a>
                        <a class="collapse-item" asp-controller="ResponsablesInstitucionales" asp-action="Index">ResponsableInstitucional</a>
                        <a class="collapse-item" asp-controller="AsesoresInstitucionales" asp-action="Index">AsesorInstitucional</a>
                        <a class="collapse-item" asp-controller="MentoresAcademicos" asp-action="Index">MentoresAcademicos</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Reportes Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseAsignaturas">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Asignaturas</span>
                </a>
                <div id="collapseAsignaturas" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-controller="Asignaturas" asp-action="Index">Asignaturas</a>

                    </div>
                </div>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseBecas">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Becas</span>
                </a>
                <div id="collapseBecas" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-controller="BecasDuales" asp-action="Index">Becas</a>

                    </div>
                </div>
            </li>


            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseProyecto">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Catalago Proyectos</span>
                </a>
                <div id="collapseProyecto" class="collapse" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <a class="collapse-item" asp-controller="CatalagoProyectos" asp-action="NuevoProyecto">Nuevo</a>
                        <a class="collapse-item" asp-controller="CatalagoProyectos" asp-action="ReporteProyectos">Reporte</a>

                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">
            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
                                <img class="img-profile rounded-circle"
                                     src="https://images.unsplash.com/photo-1519648023493-d82b5f8d7b8a?w=300">
                            </a>
                            <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                 aria-labelledby="userDropdown">
                                <a class="dropdown-item" asp-controller="Home" asp-action="Perfil">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Perfil
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Salir
                                </a>
                            </div>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->
    <!-- Bootstrap core JavaScript-->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/js/sb-admin-2.js"></script>
    <script src="~/vendor/toastr/toastr.min.js"></script>
    <script src="~/vendor/sweetalert/sweetalert.js"></script>
    <script src="~/vendor/loadingoverlay/loadingoverlay.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>